repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-added-large-files
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.15.0
      hooks:
          - id: eslint
            types: [file]
            files: \.(svelte|js|ts)$
            additional_dependencies:
                - eslint
                - svelte
                - typescript
                - eslint-plugin-svelte3
                - '@typescript-eslint/eslint-plugin'
                - '@typescript-eslint/parser'
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.6.2
      hooks:
          - id: prettier
            args: [--config, .prettierrc.yml, --write] # edit files in-place
            additional_dependencies:
                - prettier
                - prettier-plugin-svelte
                - svelte
